coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "tests/"
  - "examples/"
  - "benches/"
  - "generate_all_ascii_titles.rs"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false